# Generated by Django 5.2.9 on 2025-12-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='preferred_block',
            field=models.CharField(blank=True, choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_room_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Sharing'), ('double', 'Double Sharing'), ('triple', 'Triple Sharing')], max_length=10, null=True),
        ),
    ]
