# Generated by Django 5.2.9 on 2025-12-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_student_preferred_block_student_preferred_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='block',
            field=models.CharField(choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Sharing'), ('double', 'Double Sharing'), ('triple', 'Triple Sharing')], default='single', max_length=10),
            preserve_default=False,
        ),
    ]
